FROM pgvector/pgvector:pg17

COPY init-db.sh /docker-entrypoint-initdb.d/01-init-db.sh
COPY rag_db_aligned.dump /docker-entrypoint-initdb.d/backup_main.dump
COPY companies_aligned.dump /docker-entrypoint-initdb.d/backup_companies.dump
